name: SVG diff
on: [push]

jobs:
    svgTester:
        runs-on: ubuntu-latest

        steps:
            - name: Clone repository
              uses: actions/checkout@v3

            - uses: ./.github/actions/setup-node-yarn-deps
            - uses: ./.github/actions/build-tsc

            - name: Set branch name for OWID runs
              if: ${{ GITHUB_REPOSITORY_OWNER == 'owid' }}
              shell: bash
              run: echo "PUSH_BRANCH_NAME=${{ GITHUB_REF_NAME }}" >> $GITHUB_ENV

            - name: Set branch name for forks
              if: ${{ GITHUB_REPOSITORY_OWNER != 'owid' }}
              shell: bash
              run: echo "PUSH_BRANCH_NAME=${{ GITHUB_REPOSITORY_OWNER }}/${{ GITHUB_REF_NAME }}" >> $GITHUB_ENV

            - name: Print branch name
              shell: bash
              run: echo "${{env.PUSH_BRANCH_NAME}}"

            # Checkout the owid-grapher-svgs repo into a subfolder. Use a Personal Access Token for checkout so the
            # action will have permission to push later on if required.
            - name: Clone svg tester repo
              uses: actions/checkout@v3
              with:
                  repository: "owid/owid-grapher-svgs"
                  path: owid-grapher-svgs
                  token: ${{ secrets.GITHUBPAT }}

            # Switch to or create a branch on that repo that matches the branch name we are on in the owid-grapher repo
            # but only do this if we are not on master in owid-graphers (in this case we want to commit and push on master
            # in owid-grapher-svgs as well)
            - name: create owid-grapher-svgs local branch
              if: ${{ env.PUSH_BRANCH_NAME != 'master'}}
              working-directory: owid-grapher-svgs
              run: git branch ${{ env.PUSH_BRANCH_NAME }} && git checkout ${{ env.PUSH_BRANCH_NAME }}

            # Run the verify tool overwriting any svgs. Stdout is piped to compare-result which will be a 0 byte file if everything works or contain failed grapher ids otherwise
            - name: Run tests & checks
              id: run-verify-graphs
              continue-on-error: true
              run: node itsJustJavascript/devTools/svgTester/verify-graphs.js -i owid-grapher-svgs/configs -o owid-grapher-svgs/svg -r owid-grapher-svgs/svg > compare-result

            # If the last step failed we want to commit all changed svgs and push them to the new branch on the owid-grapher-svgs repo
            - uses: stefanzweifel/git-auto-commit-action@v4
              if: ${{ steps.run-verify-graphs.outcome == 'failure' }}
              with:
                  repository: ./owid-grapher-svgs/
                  branch: ${{ env.PUSH_BRANCH_NAME }}
                  push_options: "--force"
                  commit_message: Automated commit with svg differences triggered by commit https://github.com/owid/owid-grapher/commit/${{github.sha}}

            # We make the action fail if there were any differences and if we are on a branch other than master. On master
            # we do not want to fail because the differences on master are intended to be authorative and thus there is no
            # reason to mark this action as failed.
            - name: Fail with error message if we had differences
              if: ${{ steps.run-verify-graphs.outcome == 'failure' && env.PUSH_BRANCH_NAME != 'master' }}
              uses: actions/github-script@v3
              with:
                  script: |
                      core.setFailed('SVGs were different from reference! Please check diffs at https://github.com/owid/owid-grapher-svgs/commits/${{ env.PUSH_BRANCH_NAME }}')
